### ISSUE TITLE
WidgetContent crud search id

### ISSUE THREAD

**Issue by J-Reichl** [dmstr/yii2-widgets2-module#29]
Searching for an id within the widget content crud throws an 'Integrity constraint violation' exception.
at (pageUrl)/widgets/crud/widget/index
![screen shot 2018-12-05 at 10 52 51](https://user-images.githubusercontent.com/18026410/49506038-57a79100-f87d-11e8-82ef-38bcf1c62051.png)

**Comment by handcode** [comment]
@work, see #30
