### ISSUE TITLE
initJSONEditorsPlugins not always  executed

### ISSUE THREAD

**Issue by handcode** [dmstr/yii2-widgets2-module#32]
initJSONEditorsPlugins is not always executed.

Therefore plugins (ckeditor) are not always loaded correctly.

Q&D fix see: 2db462e553cc18f45250e9e49a41fda2e9f6d735

**Comment by schmunk42** [comment]
Possibly related to https://jquery.com/upgrade-guide/3.0/#breaking-change-document-ready-handlers-are-now-asynchronous in jQuery 3

**Comment by handcode** [comment]
Should be fixed with new JsonEditorWidget option `registerPluginAsset`.
see: https://github.com/dmstr/yii2-json-editor/pull/26
